# Generated by Django 3.1.4 on 2021-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20210304_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Kebab', 'Kebab'), ('Italian', 'Italian'), ('Asian', 'Asian'), ('Sushi', 'Sushi'), ('Polish', 'Polish'), ('Burger', 'Burger'), ('VEGAN', 'VEGAN')], max_length=15, null=True),
        ),
    ]
